# Copyright 2018, alex at staticlibs.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# updated: 2021-02-16

FROM ubuntu:focal
ADD openssl.cnf /opt/openssl.cnf
RUN export DEBIAN_FRONTEND="noninteractive" && \
    export TZ="US/Pacific" && \
    apt update && \
    apt upgrade -y && \
    apt install -y \
        git \
        valgrind \
        build-essential \
        cmake \
        pkg-config \
        zip \
        openjdk-8-jdk-headless \
        zlib1g-dev \
        libjansson-dev \
        liblog4cplus-dev \
        libssl-dev \
        libcurl4-openssl-dev \
        libasio-dev \
        libpopt-dev \
        libsqlite3-dev \
        libpq-dev \
        libsoci-dev \
        libpng-dev \
        libhpdf-dev \
        libglib2.0-dev \
        libjavascriptcoregtk-4.0-dev \
        libgtk-3-dev \
        libwebkit2gtk-4.0-dev \
        libssh2-1-dev \
        libgit2-dev \
        libsystemd-dev \
        libjpeg-turbo8-dev && \
    apt autoremove -y && \
    apt clean
